---
- name: Update all packages
  yum: name=* state=latest
   
- name: Install Docker
  yum: pkg=docker state=present 

- name: Install docker-compose
  get_url: 
    url : https://github.com/docker/compose/releases/download/1.25.1-rc1/docker-compose-Linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: 'u+x,g+x'

- name: Start Docker service
  service:
    name: docker
    state: started
    enabled: yes

- name: Create Wordpress Directory 
  file: 
    path: /etc/wordpress/
    state: directory

- name: Transfer Docker-Compose files to remote hosts
  copy:
    src: ./docker/wordpress/docker-compose.yml
    dest: /etc/wordpress/docker-compose.yml
    
- name: Run `docker-compose up`
  shell: HOST={{wp_db_host}} DB_NAME={{wp_db_name}} DB_USER={{wp_db_user}} DB_PASSWORD={{wp_db_password}} docker-compose up -d 
  args:
    chdir: /etc/wordpress/